development:
  dialect: postgres
  database: bookings
  user: postgres
  password: 12032004
  host: 127.0.0.1
  pool: 5
  port: 2345

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:2345/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:2345/myapp_production"}}
